# Global settings applied to the whole site.
[build]
  command = "npm run build:all"
  publish = "dist/shell/browser"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/shell/browser/index.html"
  status = 200

[[redirects]]
  from = "/microfrontend-a/*"
  to = "/microfrontend-a/browser/index.html"
  status = 200

[[redirects]]
  from = "/microfrontend-b/*"
  to = "/microfrontend-b/browser/index.html"
  status = 200

