import*as i from"@angular/core";import{inject as l,\u0275ChangeDetectionScheduler as A,RendererFactory2 as v,NgZone as N,ANIMATION_MODULE_TYPE as c,\u0275performanceMarkFeature as y}from"@angular/core";import{ANIMATION_MODULE_TYPE as k}from"@angular/core";import{\u0275DomRendererFactory2 as D,BrowserModule as d}from"@angular/platform-browser";import*as o from"@angular/animations/browser";import{\u0275AnimationEngine as r,\u0275WebAnimationsStyleNormalizer as M,\u0275AnimationRendererFactory as I,\u0275AnimationStyleNormalizer as g,AnimationDriver as u,\u0275WebAnimationsDriver as O,NoopAnimationDriver as R}from"@angular/animations/browser";import{DOCUMENT as E}from"@angular/common";var h=(()=>{class e extends r{constructor(t,n,f){super(t,n,f,l(A,{optional:!0}))}ngOnDestroy(){this.flush()}static{this.\u0275fac=function(n){return new(n||e)(i.\u0275\u0275inject(E),i.\u0275\u0275inject(o.AnimationDriver),i.\u0275\u0275inject(o.\u0275AnimationStyleNormalizer))}}static{this.\u0275prov=i.\u0275\u0275defineInjectable({token:e,factory:e.\u0275fac})}}return e})();function S(){return new M}function j(e,p,t){return new I(e,p,t)}var m=[{provide:g,useFactory:S},{provide:r,useClass:h},{provide:v,useFactory:j,deps:[D,r,N]}],a=[{provide:u,useFactory:()=>new O},{provide:c,useValue:"BrowserAnimations"},...m],s=[{provide:u,useClass:R},{provide:c,useValue:"NoopAnimations"},...m],V=(()=>{class e{static withConfig(t){return{ngModule:e,providers:t.disableAnimations?s:a}}static{this.\u0275fac=function(n){return new(n||e)}}static{this.\u0275mod=i.\u0275\u0275defineNgModule({type:e})}static{this.\u0275inj=i.\u0275\u0275defineInjector({providers:a,imports:[d]})}}return e})();function z(){return y("NgEagerAnimations"),[...a]}var B=(()=>{class e{static{this.\u0275fac=function(n){return new(n||e)}}static{this.\u0275mod=i.\u0275\u0275defineNgModule({type:e})}static{this.\u0275inj=i.\u0275\u0275defineInjector({providers:s,imports:[d]})}}return e})();function W(){return[...s]}export{k as ANIMATION_MODULE_TYPE,V as BrowserAnimationsModule,B as NoopAnimationsModule,z as provideAnimations,W as provideNoopAnimations,h as \u0275InjectableAnimationEngine};
/*! Bundled license information:

@angular/platform-browser/fesm2022/animations.mjs:
  (**
   * @license Angular v17.3.3
   * (c) 2010-2022 Google LLC. https://angular.io/
   * License: MIT
   *)
*/
